import type { Locale } from './site';

type Dictionary = Record<string, string>;

const en: Dictionary = {
  'nav.apps': 'Apps',
  'nav.about': 'About',
  'nav.contact': 'Contact',
  'nav.feedback': 'Feedback',
  'nav.testers': 'Android Testers',
  'nav.privacy': 'Privacy',
  'nav.cookies': 'Cookies',
  'nav.support': 'Support',
  'nav.home': 'Home',
  'nav.skip': 'Skip to content',
  'nav.menu': 'Primary',
  'theme.label': 'Color theme',
  'theme.toLight': 'Switch to light theme',
  'theme.toDark': 'Switch to dark theme',
  'lang.label': 'Language',
  'lang.en': 'English',
  'lang.es': 'Español',
  'lang.ca': 'Català',
  'lang.fr': 'Français',
  'lang.de': 'Deutsch',
  'lang.it': 'Italiano',
  'hero.title': 'Apps by 0xVera',
  'hero.subtitle':
    'Independent applications designed around utility, privacy and straightforward user experiences.',
  'catalog.title': 'Applications',
  'catalog.subtitle': 'Browse published and upcoming apps from 0xVera.',
  'catalog.viewDetails': 'View details',
  'catalog.empty': 'No applications are listed yet.',
  'about.title': 'About',
  'about.body':
    '0xVera builds independent applications designed around utility, privacy and straightforward user experiences.',
  'contact.title': 'Contact',
  'contact.supportLabel': 'App support',
  'contact.generalLabel': 'General contact',
  'contact.supportHint': 'For questions about a specific application.',
  'contact.generalHint': 'For general inquiries about 0xVera.',
  'status.available': 'Available',
  'status.coming-soon': 'Coming soon',
  'status.beta-testing': 'Beta testers open',
  'status.in-development': 'In development',
  'status.unavailable': 'Unavailable',
  'price.free': 'Free',
  'price.paid': 'Paid',
  'price.freemium': 'Freemium',
  'platform.android': 'Android',
  'platform.ios': 'iOS',
  'platform.web': 'Web',
  'app.developer': 'Developer',
  'app.status': 'Status',
  'app.platforms': 'Platforms',
  'app.price': 'Price',
  'app.version': 'Version',
  'app.updated': 'Updated',
  'app.minimumAndroid': 'Minimum Android',
  'app.minimumIos': 'Minimum iOS',
  'app.hasAds': 'Advertising',
  'app.hasAnalytics': 'Analytics',
  'app.requiresAccount': 'Account required',
  'app.worksOffline': 'Works offline',
  'app.yes': 'Yes',
  'app.no': 'No',
  'app.features': 'Features',
  'app.permissions': 'Permissions',
  'app.screenshots': 'Screenshots',
  'app.links': 'Links',
  'app.privacy': 'Privacy policy',
  'app.support': 'Support',
  'app.terms': 'Terms',
  'app.web': 'Website',
  'app.repository': 'Repository',
  'app.playStore': 'Google Play',
  'app.appStore': 'App Store',
  'app.comingSoonPlay': 'Coming soon on Google Play',
  'app.comingSoonStore': 'Coming soon',
  'app.comingSoonAppStore': 'Coming soon on the App Store',
  'app.joinBetaTesters': 'Join Android beta testers',
  'app.backToCatalog': 'Back to apps',
  'app.giveFeedback': 'Give feedback',
  'app.joinTesting': 'Join testing',
  'app.incompleteNotice':
    'Some details for this application are still being prepared and will be updated before publication.',
  'feedback.seoTitle': 'App Feedback | 0xVera',
  'feedback.seoDescription':
    'Report bugs, suggest improvements and share feedback about 0xVera apps.',
  'feedback.title': 'App Feedback',
  'feedback.titleForApp': 'Feedback for {app}',
  'feedback.intro':
    'Help us improve 0xVera apps by reporting bugs, suggesting improvements or sharing your honest experience.',
  'feedback.chooseLanguage': 'Choose your preferred language to open the feedback form.',
  'feedback.formsLanguages': 'Feedback forms are currently available in English and Spanish.',
  'feedback.optionEn': 'English',
  'feedback.optionEs': 'Español',
  'feedback.scope':
    'Your feedback can include bug reports, usability issues, feature requests, performance problems, privacy or security concerns, design feedback and general suggestions.',
  'feedback.accountNote':
    'Feedback forms require a Google account and record the verified email address associated with the submission. This is used to identify tester feedback, prevent abuse and allow follow-up when necessary.',
  'feedback.warning':
    'Please do not submit passwords, private keys, seed phrases, identity documents, payment information or other sensitive information.',
  'feedback.support': 'For support, contact {email}.',
  'testers.seoTitle': 'Android Testers | 0xVera',
  'testers.seoDescription':
    'Join the 0xVera Android testing community and get early access to selected apps.',
  'testers.title': 'Join 0xVera Android Testers',
  'testers.intro':
    'Get early access to selected 0xVera Android apps and help us improve them before public release.',
  'testers.body':
    'Joining the tester community gives you access to invitations for upcoming Android tests.\n\nEach app has its own Google Play testing programme. Being a member of this group does not automatically enrol you in every test — you choose which apps you want to try.',
  'testers.googleAccountRequired':
    'A Google account is required to join Android closed tests through Google Play.',
  'testers.voluntary':
    'Participation is voluntary. You can leave the group at any time. Honest, detailed feedback is always appreciated.',
  'testers.cta': 'Join the tester community',
  'testers.ctaMailtoHint':
    'Open your email client to request access via the Google Group address below.',
  'testers.groupEmailLabel': 'Group email',
  'testers.alreadyTesting': 'Already testing an app?',
  'testers.shareFeedback': 'Share your feedback',
  'testers.privacyTitle': 'Privacy',
  'testers.privacyBody':
    'Group membership is managed through Google Groups. Google may process data associated with your Google account under its own policies. 0xVera does not need to publish the member list. You can leave the group whenever you want.\n\nFeedback forms require a Google account and record the verified email address associated with the submission. This is used to identify tester feedback, prevent abuse and allow follow-up when necessary. Submissions are stored with Google Forms/Sheets. Do not send sensitive data.',
  'footer.identity': '0xVera',
  'footer.tagline': 'Independent applications with a focus on utility and privacy.',
  'footer.rights': 'All rights reserved.',
  'consent.title': 'Analytics preference',
  'consent.body':
    'We use optional analytics to understand aggregate usage of this site. No analytics cookies are set until you accept.',
  'consent.accept': 'Accept analytics',
  'consent.reject': 'Reject',
  'consent.manage': 'Manage analytics',
  'notFound.title': 'Page not found',
  'notFound.body': 'The page you requested does not exist or has been moved.',
  'notFound.cta': 'Return home',
  'legal.draftNotice': 'This page is temporary and not ready for indexing.',
  'legal.updated': 'Last updated',
  'legal.fallbackNotice': 'Legal pages are provided in English for now.',
  'support.title': 'Support',
  'support.emailLabel': 'Email support',
  'support.includeTitle': 'Please include',
  'support.warningTitle': 'Do not send sensitive data',
};

const es: Dictionary = {
  ...en,
  'nav.about': 'Acerca de',
  'nav.contact': 'Contacto',
  'nav.feedback': 'Feedback',
  'nav.testers': 'Android Testers',
  'nav.privacy': 'Privacidad',
  'nav.cookies': 'Cookies',
  'nav.support': 'Soporte',
  'nav.home': 'Inicio',
  'nav.skip': 'Saltar al contenido',
  'nav.menu': 'Principal',
  'theme.label': 'Tema de color',
  'theme.toLight': 'Cambiar a tema claro',
  'theme.toDark': 'Cambiar a tema oscuro',
  'lang.label': 'Idioma',
  'hero.title': 'Apps de 0xVera',
  'hero.subtitle':
    'Aplicaciones independientes diseñadas en torno a la utilidad, la privacidad y una experiencia directa.',
  'catalog.title': 'Aplicaciones',
  'catalog.subtitle': 'Explora las apps publicadas y próximas de 0xVera.',
  'catalog.viewDetails': 'Ver detalles',
  'catalog.empty': 'Todavía no hay aplicaciones listadas.',
  'about.title': 'Acerca de',
  'about.body':
    '0xVera crea aplicaciones independientes centradas en la utilidad, la privacidad y una experiencia directa.',
  'contact.title': 'Contacto',
  'contact.supportLabel': 'Soporte de apps',
  'contact.generalLabel': 'Contacto general',
  'contact.supportHint': 'Para preguntas sobre una aplicación concreta.',
  'contact.generalHint': 'Para consultas generales sobre 0xVera.',
  'status.available': 'Disponible',
  'status.coming-soon': 'Próximamente',
  'status.beta-testing': 'Beta testers abiertos',
  'status.in-development': 'En desarrollo',
  'status.unavailable': 'No disponible',
  'price.free': 'Gratis',
  'price.paid': 'De pago',
  'app.developer': 'Desarrollador',
  'app.status': 'Estado',
  'app.platforms': 'Plataformas',
  'app.price': 'Precio',
  'app.version': 'Versión',
  'app.updated': 'Actualización',
  'app.minimumAndroid': 'Android mínimo',
  'app.minimumIos': 'iOS mínimo',
  'app.hasAds': 'Publicidad',
  'app.hasAnalytics': 'Analítica',
  'app.requiresAccount': 'Requiere cuenta',
  'app.worksOffline': 'Funciona sin conexión',
  'app.yes': 'Sí',
  'app.no': 'No',
  'app.features': 'Funciones',
  'app.permissions': 'Permisos',
  'app.screenshots': 'Capturas',
  'app.links': 'Enlaces',
  'app.privacy': 'Política de privacidad',
  'app.support': 'Soporte',
  'app.terms': 'Términos',
  'app.web': 'Sitio web',
  'app.repository': 'Repositorio',
  'app.comingSoonPlay': 'Próximamente en Google Play',
  'app.comingSoonStore': 'Próximamente',
  'app.comingSoonAppStore': 'Próximamente en App Store',
  'app.joinBetaTesters': 'Unirse a los beta testers de Android',
  'app.backToCatalog': 'Volver a las apps',
  'app.giveFeedback': 'Enviar feedback',
  'app.joinTesting': 'Unirse al testing',
  'app.incompleteNotice':
    'Algunos detalles de esta aplicación todavía se están preparando y se actualizarán antes de su publicación.',
  'feedback.seoTitle': 'Feedback de las apps | 0xVera',
  'feedback.seoDescription':
    'Informa de errores, sugiere mejoras y comparte tu opinión sobre las apps de 0xVera.',
  'feedback.title': 'Feedback de las apps',
  'feedback.titleForApp': 'Feedback sobre {app}',
  'feedback.intro':
    'Ayúdanos a mejorar las apps de 0xVera informando de errores, sugiriendo mejoras o compartiendo tu experiencia sincera.',
  'feedback.chooseLanguage': 'Elige el idioma del formulario de feedback.',
  'feedback.formsLanguages':
    'Los formularios de feedback están disponibles por ahora en inglés y español.',
  'feedback.optionEn': 'English',
  'feedback.optionEs': 'Español',
  'feedback.scope':
    'Tu feedback puede incluir informes de errores, problemas de usabilidad, peticiones de funciones, rendimiento, privacidad o seguridad, diseño y sugerencias generales.',
  'feedback.accountNote':
    'Los formularios de feedback requieren una cuenta de Google y registran la dirección de correo verificada asociada al envío. Se usa para identificar el feedback de testers, prevenir abusos y poder hacer seguimiento cuando haga falta.',
  'feedback.warning':
    'No envíes contraseñas, claves privadas, frases semilla, documentos de identidad, información de pago ni otros datos sensibles.',
  'feedback.support': 'Para soporte, escribe a {email}.',
  'testers.seoTitle': 'Android Testers | 0xVera',
  'testers.seoDescription':
    'Únete a la comunidad de testing Android de 0xVera y prueba apps seleccionadas antes del lanzamiento.',
  'testers.title': 'Únete a 0xVera Android Testers',
  'testers.intro':
    'Consigue acceso anticipado a algunas apps Android de 0xVera y ayúdanos a mejorarlas antes del lanzamiento público.',
  'testers.body':
    'Al unirte a la comunidad de testers podrás recibir invitaciones a próximas pruebas en Android.\n\nCada app tiene su propio programa de testing en Google Play. Formar parte de este grupo no te inscribe automáticamente en todas las pruebas: tú decides en cuáles quieres participar.',
  'testers.googleAccountRequired':
    'Se necesita una cuenta de Google para unirse a las pruebas cerradas de Android a través de Google Play.',
  'testers.voluntary':
    'La participación es voluntaria. Puedes abandonar el grupo en cualquier momento. Agradecemos el feedback honesto y detallado.',
  'testers.cta': 'Unirse a la comunidad de testers',
  'testers.ctaMailtoHint':
    'Abre tu cliente de correo para solicitar acceso con la dirección del Google Group indicada abajo.',
  'testers.groupEmailLabel': 'Email del grupo',
  'testers.alreadyTesting': '¿Ya estás probando una app?',
  'testers.shareFeedback': 'Comparte tu feedback',
  'testers.privacyTitle': 'Privacidad',
  'testers.privacyBody':
    'La membresía del grupo se gestiona mediante Google Groups. Google puede tratar los datos asociados a tu cuenta de Google según sus propias políticas. 0xVera no necesita publicar la lista de miembros. Puedes abandonar el grupo cuando quieras.\n\nLos formularios de feedback requieren una cuenta de Google y registran la dirección de correo verificada asociada al envío. Se usa para identificar el feedback de testers, prevenir abusos y poder hacer seguimiento cuando haga falta. Las respuestas se almacenan con Google Forms/Sheets. No envíes datos sensibles.',
  'footer.tagline': 'Aplicaciones independientes con foco en utilidad y privacidad.',
  'footer.rights': 'Todos los derechos reservados.',
  'consent.title': 'Preferencia de analítica',
  'consent.body':
    'Usamos analítica opcional para entender el uso agregado de este sitio. No se establecen cookies de analítica hasta que aceptes.',
  'consent.accept': 'Aceptar analítica',
  'consent.reject': 'Rechazar',
  'consent.manage': 'Gestionar analítica',
  'notFound.title': 'Página no encontrada',
  'notFound.body': 'La página solicitada no existe o se ha movido.',
  'notFound.cta': 'Volver al inicio',
  'legal.draftNotice': 'Esta página es temporal y no está lista para indexación.',
  'legal.updated': 'Última actualización',
  'legal.fallbackNotice':
    'Las páginas legales se ofrecen en inglés por ahora.',
  'support.title': 'Soporte',
  'support.emailLabel': 'Soporte por email',
  'support.includeTitle': 'Incluye, si puedes',
  'support.warningTitle': 'No envíes datos sensibles',
};

const ca: Dictionary = {
  ...en,
  'nav.about': 'Quant a',
  'nav.contact': 'Contacte',
  'nav.privacy': 'Privadesa',
  'nav.home': 'Inici',
  'nav.skip': 'Salta al contingut',
  'nav.menu': 'Principal',
  'theme.label': 'Tema de color',
  'theme.toLight': 'Canvia al tema clar',
  'theme.toDark': 'Canvia al tema fosc',
  'lang.label': 'Idioma',
  'hero.title': 'Apps de 0xVera',
  'hero.subtitle':
    'Aplicacions independents pensades per a la utilitat, la privadesa i una experiència directa.',
  'catalog.title': 'Aplicacions',
  'catalog.subtitle': 'Explora les apps publicades i properes de 0xVera.',
  'catalog.viewDetails': 'Veure detalls',
  'catalog.empty': 'Encara no hi ha aplicacions llistades.',
  'about.title': 'Quant a',
  'about.body':
    '0xVera crea aplicacions independents centrades en la utilitat, la privadesa i una experiència directa.',
  'contact.title': 'Contacte',
  'contact.supportLabel': 'Suport d’apps',
  'contact.generalLabel': 'Contacte general',
  'contact.supportHint': 'Per a preguntes sobre una aplicació concreta.',
  'contact.generalHint': 'Per a consultes generals sobre 0xVera.',
  'status.available': 'Disponible',
  'status.coming-soon': 'Properament',
  'status.beta-testing': 'Beta testers oberts',
  'status.in-development': 'En desenvolupament',
  'status.unavailable': 'No disponible',
  'app.joinBetaTesters': 'Uneix-te als beta testers d’Android',
  'feedback.formsLanguages':
    'Els formularis de feedback estan disponibles de moment en anglès i espanyol.',
  'feedback.accountNote':
    'Els formularis de feedback requereixen un compte de Google i registren l’adreça de correu verificada associada a l’enviament. S’utilitza per identificar el feedback dels testers, prevenir abusos i fer seguiment quan calgui.',
  'testers.googleAccountRequired':
    'Cal un compte de Google per unir-se a les proves tancades d’Android a través de Google Play.',
  'testers.privacyBody':
    'La pertinença al grup es gestiona amb Google Groups. Google pot tractar les dades associades al teu compte de Google segons les seves pròpies polítiques. 0xVera no necessita publicar la llista de membres. Pots deixar el grup quan vulguis.\n\nEls formularis de feedback requereixen un compte de Google i registren l’adreça de correu verificada associada a l’enviament. S’utilitza per identificar el feedback dels testers, prevenir abusos i fer seguiment quan calgui. Les respostes s’emmagatzemen amb Google Forms/Sheets. No enviïs dades sensibles.',
  'price.free': 'Gratuïta',
  'price.paid': 'De pagament',
  'app.developer': 'Desenvolupador',
  'app.status': 'Estat',
  'app.platforms': 'Plataformes',
  'app.price': 'Preu',
  'app.version': 'Versió',
  'app.updated': 'Actualització',
  'app.minimumAndroid': 'Android mínim',
  'app.minimumIos': 'iOS mínim',
  'app.hasAds': 'Publicitat',
  'app.hasAnalytics': 'Analítica',
  'app.requiresAccount': 'Requereix compte',
  'app.worksOffline': 'Funciona sense connexió',
  'app.yes': 'Sí',
  'app.no': 'No',
  'app.features': 'Funcions',
  'app.permissions': 'Permisos',
  'app.screenshots': 'Captures',
  'app.links': 'Enllaços',
  'app.privacy': 'Política de privadesa',
  'app.support': 'Suport',
  'app.terms': 'Termes',
  'app.web': 'Lloc web',
  'app.repository': 'Repositori',
  'app.comingSoonPlay': 'Properament a Google Play',
  'app.comingSoonStore': 'Properament',
  'app.comingSoonAppStore': 'Properament a l’App Store',
  'app.backToCatalog': 'Tornar a les apps',
  'app.incompleteNotice':
    'Alguns detalls d’aquesta aplicació encara s’estan preparant i s’actualitzaran abans de la publicació.',
  'footer.tagline': 'Aplicacions independents amb focus en utilitat i privadesa.',
  'footer.rights': 'Tots els drets reservats.',
  'consent.title': 'Preferència d’analítica',
  'consent.body':
    'Fem servir analítica opcional per entendre l’ús agregat d’aquest lloc. No s’estableixen galetes d’analítica fins que ho acceptis.',
  'consent.accept': 'Acceptar analítica',
  'consent.reject': 'Rebutjar',
  'consent.manage': 'Gestionar analítica',
  'notFound.title': 'Pàgina no trobada',
  'notFound.body': 'La pàgina sol·licitada no existeix o s’ha mogut.',
  'notFound.cta': 'Tornar a l’inici',
  'legal.draftNotice': 'Aquesta pàgina és temporal i no està llesta per a indexació.',
  'legal.updated': 'Darrera actualització',
  'legal.fallbackNotice':
    'Les pàgines legals s’ofereixen en anglès de moment.',
  'support.title': 'Suport',
  'support.emailLabel': 'Suport per correu',
  'support.includeTitle': 'Inclou, si pots',
  'support.warningTitle': 'No enviïs dades sensibles',
};

const fr: Dictionary = {
  ...en,
  'nav.about': 'À propos',
  'nav.contact': 'Contact',
  'nav.privacy': 'Confidentialité',
  'nav.home': 'Accueil',
  'nav.skip': 'Aller au contenu',
  'nav.menu': 'Principal',
  'theme.label': 'Thème',
  'theme.toLight': 'Passer au thème clair',
  'theme.toDark': 'Passer au thème sombre',
  'lang.label': 'Langue',
  'hero.title': 'Apps par 0xVera',
  'hero.subtitle':
    'Applications indépendantes conçues autour de l’utilité, de la confidentialité et d’une expérience simple.',
  'catalog.title': 'Applications',
  'catalog.subtitle': 'Parcourez les apps publiées et à venir de 0xVera.',
  'catalog.viewDetails': 'Voir les détails',
  'catalog.empty': 'Aucune application n’est encore listée.',
  'about.title': 'À propos',
  'about.body':
    '0xVera crée des applications indépendantes centrées sur l’utilité, la confidentialité et une expérience simple.',
  'contact.title': 'Contact',
  'contact.supportLabel': 'Support des apps',
  'contact.generalLabel': 'Contact général',
  'contact.supportHint': 'Pour les questions sur une application précise.',
  'contact.generalHint': 'Pour les demandes générales concernant 0xVera.',
  'status.available': 'Disponible',
  'status.coming-soon': 'Bientôt',
  'status.beta-testing': 'Bêta testeurs ouverts',
  'status.in-development': 'En développement',
  'status.unavailable': 'Indisponible',
  'app.joinBetaTesters': 'Rejoindre les bêta testeurs Android',
  'feedback.formsLanguages':
    'Les formulaires de feedback sont pour l’instant disponibles en anglais et en espagnol.',
  'feedback.accountNote':
    'Les formulaires de feedback nécessitent un compte Google et enregistrent l’adresse e-mail vérifiée associée à l’envoi. Cela sert à identifier les retours des testeurs, prévenir les abus et assurer un suivi si nécessaire.',
  'testers.googleAccountRequired':
    'Un compte Google est requis pour rejoindre les tests Android fermés via Google Play.',
  'testers.privacyBody':
    'L’adhésion au groupe est gérée via Google Groups. Google peut traiter les données associées à votre compte Google selon ses propres politiques. 0xVera n’a pas besoin de publier la liste des membres. Vous pouvez quitter le groupe quand vous le souhaitez.\n\nLes formulaires de feedback nécessitent un compte Google et enregistrent l’adresse e-mail vérifiée associée à l’envoi. Cela sert à identifier les retours des testeurs, prévenir les abus et assurer un suivi si nécessaire. Les réponses sont stockées avec Google Forms/Sheets. N’envoyez pas de données sensibles.',
  'price.free': 'Gratuit',
  'price.paid': 'Payant',
  'app.developer': 'Développeur',
  'app.status': 'Statut',
  'app.platforms': 'Plateformes',
  'app.price': 'Prix',
  'app.version': 'Version',
  'app.updated': 'Mise à jour',
  'app.minimumAndroid': 'Android minimum',
  'app.minimumIos': 'iOS minimum',
  'app.hasAds': 'Publicité',
  'app.hasAnalytics': 'Analytique',
  'app.requiresAccount': 'Compte requis',
  'app.worksOffline': 'Fonctionne hors ligne',
  'app.yes': 'Oui',
  'app.no': 'Non',
  'app.features': 'Fonctionnalités',
  'app.permissions': 'Autorisations',
  'app.screenshots': 'Captures',
  'app.links': 'Liens',
  'app.privacy': 'Politique de confidentialité',
  'app.support': 'Support',
  'app.terms': 'Conditions',
  'app.web': 'Site web',
  'app.repository': 'Dépôt',
  'app.comingSoonPlay': 'Bientôt sur Google Play',
  'app.comingSoonStore': 'Bientôt',
  'app.comingSoonAppStore': 'Bientôt sur l’App Store',
  'app.backToCatalog': 'Retour aux apps',
  'app.incompleteNotice':
    'Certains détails de cette application sont encore en préparation et seront mis à jour avant publication.',
  'footer.tagline': 'Applications indépendantes axées sur l’utilité et la confidentialité.',
  'footer.rights': 'Tous droits réservés.',
  'consent.title': 'Préférence d’analytique',
  'consent.body':
    'Nous utilisons une analytique optionnelle pour comprendre l’usage agrégé de ce site. Aucun cookie d’analytique n’est déposé avant acceptation.',
  'consent.accept': 'Accepter l’analytique',
  'consent.reject': 'Refuser',
  'consent.manage': 'Gérer l’analytique',
  'notFound.title': 'Page introuvable',
  'notFound.body': 'La page demandée n’existe pas ou a été déplacée.',
  'notFound.cta': 'Retour à l’accueil',
  'legal.draftNotice': 'Cette page est temporaire et non prête pour l’indexation.',
  'legal.updated': 'Dernière mise à jour',
  'legal.fallbackNotice':
    'Les pages juridiques sont fournies en anglais pour le moment.',
  'support.title': 'Support',
  'support.emailLabel': 'Support par e-mail',
  'support.includeTitle': 'Merci d’inclure',
  'support.warningTitle': 'N’envoyez pas de données sensibles',
};

const de: Dictionary = {
  ...en,
  'nav.about': 'Über uns',
  'nav.contact': 'Kontakt',
  'nav.privacy': 'Datenschutz',
  'nav.home': 'Start',
  'nav.skip': 'Zum Inhalt springen',
  'nav.menu': 'Hauptnavigation',
  'theme.label': 'Farbschema',
  'theme.toLight': 'Zum hellen Design wechseln',
  'theme.toDark': 'Zum dunklen Design wechseln',
  'lang.label': 'Sprache',
  'hero.title': 'Apps von 0xVera',
  'hero.subtitle':
    'Unabhängige Anwendungen mit Fokus auf Nutzen, Privatsphäre und klarer Bedienung.',
  'catalog.title': 'Anwendungen',
  'catalog.subtitle': 'Entdecke veröffentlichte und kommende Apps von 0xVera.',
  'catalog.viewDetails': 'Details ansehen',
  'catalog.empty': 'Noch keine Anwendungen gelistet.',
  'about.title': 'Über uns',
  'about.body':
    '0xVera entwickelt unabhängige Anwendungen mit Fokus auf Nutzen, Privatsphäre und klarer Bedienung.',
  'contact.title': 'Kontakt',
  'contact.supportLabel': 'App-Support',
  'contact.generalLabel': 'Allgemeiner Kontakt',
  'contact.supportHint': 'Für Fragen zu einer bestimmten Anwendung.',
  'contact.generalHint': 'Für allgemeine Anfragen zu 0xVera.',
  'status.available': 'Verfügbar',
  'status.coming-soon': 'Demnächst',
  'status.beta-testing': 'Beta-Tester offen',
  'status.in-development': 'In Entwicklung',
  'status.unavailable': 'Nicht verfügbar',
  'app.joinBetaTesters': 'Android-Beta-Testern beitreten',
  'feedback.formsLanguages':
    'Feedback-Formulare sind derzeit auf Englisch und Spanisch verfügbar.',
  'feedback.accountNote':
    'Feedback-Formulare erfordern ein Google-Konto und speichern die verifizierte E-Mail-Adresse der Einsendung. Das dient dazu, Tester-Feedback zuzuordnen, Missbrauch zu verhindern und bei Bedarf nachzufassen.',
  'testers.googleAccountRequired':
    'Für geschlossene Android-Tests über Google Play ist ein Google-Konto erforderlich.',
  'testers.privacyBody':
    'Die Gruppenmitgliedschaft wird über Google Groups verwaltet. Google kann Daten Ihres Google-Kontos gemäß den eigenen Richtlinien verarbeiten. 0xVera muss die Mitgliederliste nicht veröffentlichen. Sie können die Gruppe jederzeit verlassen.\n\nFeedback-Formulare erfordern ein Google-Konto und speichern die verifizierte E-Mail-Adresse der Einsendung. Das dient dazu, Tester-Feedback zuzuordnen, Missbrauch zu verhindern und bei Bedarf nachzufassen. Einsendungen werden mit Google Forms/Sheets gespeichert. Senden Sie keine sensiblen Daten.',
  'price.free': 'Kostenlos',
  'price.paid': 'Kostenpflichtig',
  'app.developer': 'Entwickler',
  'app.status': 'Status',
  'app.platforms': 'Plattformen',
  'app.price': 'Preis',
  'app.version': 'Version',
  'app.updated': 'Aktualisiert',
  'app.minimumAndroid': 'Mindest-Android',
  'app.minimumIos': 'Mindest-iOS',
  'app.hasAds': 'Werbung',
  'app.hasAnalytics': 'Analytik',
  'app.requiresAccount': 'Konto erforderlich',
  'app.worksOffline': 'Offline nutzbar',
  'app.yes': 'Ja',
  'app.no': 'Nein',
  'app.features': 'Funktionen',
  'app.permissions': 'Berechtigungen',
  'app.screenshots': 'Screenshots',
  'app.links': 'Links',
  'app.privacy': 'Datenschutzrichtlinie',
  'app.support': 'Support',
  'app.terms': 'Nutzungsbedingungen',
  'app.web': 'Website',
  'app.repository': 'Repository',
  'app.comingSoonPlay': 'Demnächst bei Google Play',
  'app.comingSoonStore': 'Demnächst',
  'app.comingSoonAppStore': 'Demnächst im App Store',
  'app.backToCatalog': 'Zurück zu den Apps',
  'app.incompleteNotice':
    'Einige Details zu dieser Anwendung werden noch vorbereitet und vor der Veröffentlichung ergänzt.',
  'footer.tagline': 'Unabhängige Anwendungen mit Fokus auf Nutzen und Privatsphäre.',
  'footer.rights': 'Alle Rechte vorbehalten.',
  'consent.title': 'Analytics-Einstellung',
  'consent.body':
    'Wir nutzen optionale Analytics, um die aggregierte Nutzung dieser Website zu verstehen. Analytics-Cookies werden erst nach Zustimmung gesetzt.',
  'consent.accept': 'Analytics akzeptieren',
  'consent.reject': 'Ablehnen',
  'consent.manage': 'Analytics verwalten',
  'notFound.title': 'Seite nicht gefunden',
  'notFound.body': 'Die angeforderte Seite existiert nicht oder wurde verschoben.',
  'notFound.cta': 'Zur Startseite',
  'legal.draftNotice': 'Diese Seite ist vorläufig und noch nicht indexierbar.',
  'legal.updated': 'Zuletzt aktualisiert',
  'legal.fallbackNotice':
    'Rechtliche Seiten werden vorerst auf Englisch bereitgestellt.',
  'support.title': 'Support',
  'support.emailLabel': 'E-Mail-Support',
  'support.includeTitle': 'Bitte angeben',
  'support.warningTitle': 'Keine sensiblen Daten senden',
};

const it: Dictionary = {
  ...en,
  'nav.about': 'Informazioni',
  'nav.contact': 'Contatti',
  'nav.privacy': 'Privacy',
  'nav.home': 'Home',
  'nav.skip': 'Vai al contenuto',
  'nav.menu': 'Principale',
  'theme.label': 'Tema',
  'theme.toLight': 'Passa al tema chiaro',
  'theme.toDark': 'Passa al tema scuro',
  'lang.label': 'Lingua',
  'hero.title': 'App di 0xVera',
  'hero.subtitle':
    'Applicazioni indipendenti pensate per utilità, privacy ed esperienze semplici.',
  'catalog.title': 'Applicazioni',
  'catalog.subtitle': 'Sfoglia le app pubblicate e in arrivo di 0xVera.',
  'catalog.viewDetails': 'Vedi dettagli',
  'catalog.empty': 'Non ci sono ancora applicazioni elencate.',
  'about.title': 'Informazioni',
  'about.body':
    '0xVera crea applicazioni indipendenti incentrate su utilità, privacy ed esperienze semplici.',
  'contact.title': 'Contatti',
  'contact.supportLabel': 'Supporto app',
  'contact.generalLabel': 'Contatto generale',
  'contact.supportHint': 'Per domande su un’applicazione specifica.',
  'contact.generalHint': 'Per richieste generali su 0xVera.',
  'status.available': 'Disponibile',
  'status.coming-soon': 'In arrivo',
  'status.beta-testing': 'Beta tester aperti',
  'status.in-development': 'In sviluppo',
  'status.unavailable': 'Non disponibile',
  'app.joinBetaTesters': 'Unisciti ai beta tester Android',
  'feedback.formsLanguages':
    'I moduli di feedback sono al momento disponibili in inglese e spagnolo.',
  'feedback.accountNote':
    'I moduli di feedback richiedono un account Google e registrano l’indirizzo email verificato associato all’invio. Serve a identificare il feedback dei tester, prevenire abusi e consentire un follow-up quando necessario.',
  'testers.googleAccountRequired':
    'È necessario un account Google per partecipare ai test Android chiusi tramite Google Play.',
  'testers.privacyBody':
    'L’iscrizione al gruppo è gestita tramite Google Groups. Google può trattare i dati associati al tuo account Google secondo le proprie policy. 0xVera non ha bisogno di pubblicare l’elenco dei membri. Puoi lasciare il gruppo in qualsiasi momento.\n\nI moduli di feedback richiedono un account Google e registrano l’indirizzo email verificato associato all’invio. Serve a identificare il feedback dei tester, prevenire abusi e consentire un follow-up quando necessario. Le risposte sono archiviate con Google Forms/Sheets. Non inviare dati sensibili.',
  'price.free': 'Gratuita',
  'price.paid': 'A pagamento',
  'app.developer': 'Sviluppatore',
  'app.status': 'Stato',
  'app.platforms': 'Piattaforme',
  'app.price': 'Prezzo',
  'app.version': 'Versione',
  'app.updated': 'Aggiornamento',
  'app.minimumAndroid': 'Android minimo',
  'app.minimumIos': 'iOS minimo',
  'app.hasAds': 'Pubblicità',
  'app.hasAnalytics': 'Analitica',
  'app.requiresAccount': 'Account richiesto',
  'app.worksOffline': 'Funziona offline',
  'app.yes': 'Sì',
  'app.no': 'No',
  'app.features': 'Funzioni',
  'app.permissions': 'Permessi',
  'app.screenshots': 'Screenshot',
  'app.links': 'Link',
  'app.privacy': 'Informativa sulla privacy',
  'app.support': 'Supporto',
  'app.terms': 'Termini',
  'app.web': 'Sito web',
  'app.repository': 'Repository',
  'app.comingSoonPlay': 'Presto su Google Play',
  'app.comingSoonStore': 'Presto',
  'app.comingSoonAppStore': 'Presto sull’App Store',
  'app.backToCatalog': 'Torna alle app',
  'app.incompleteNotice':
    'Alcuni dettagli di questa applicazione sono ancora in preparazione e verranno aggiornati prima della pubblicazione.',
  'footer.tagline': 'Applicazioni indipendenti con attenzione a utilità e privacy.',
  'footer.rights': 'Tutti i diritti riservati.',
  'consent.title': 'Preferenza analytics',
  'consent.body':
    'Usiamo analytics opzionali per capire l’uso aggregato di questo sito. Nessun cookie analytics viene impostato prima del consenso.',
  'consent.accept': 'Accetta analytics',
  'consent.reject': 'Rifiuta',
  'consent.manage': 'Gestisci analytics',
  'notFound.title': 'Pagina non trovata',
  'notFound.body': 'La pagina richiesta non esiste o è stata spostata.',
  'notFound.cta': 'Torna alla home',
  'legal.draftNotice': 'Questa pagina è temporanea e non è pronta per l’indicizzazione.',
  'legal.updated': 'Ultimo aggiornamento',
  'legal.fallbackNotice':
    'Le pagine legali sono fornite in inglese per ora.',
  'support.title': 'Supporto',
  'support.emailLabel': 'Supporto email',
  'support.includeTitle': 'Includi, se puoi',
  'support.warningTitle': 'Non inviare dati sensibili',
};

const dictionaries: Record<Locale, Dictionary> = { en, es, ca, fr, de, it };

export function t(locale: Locale, key: string): string {
  return dictionaries[locale][key] ?? dictionaries.en[key] ?? key;
}
