import type { Locale } from './site';

type Dictionary = Record<string, string>;

const en: Dictionary = {
  'nav.apps': 'Apps',
  'nav.about': 'About',
  'nav.contact': 'Contact',
  'nav.privacy': 'Privacy',
  'nav.cookies': 'Cookies',
  'nav.home': 'Home',
  'nav.skip': 'Skip to content',
  'nav.menu': 'Primary',
  'theme.label': 'Color theme',
  'theme.light': 'Light',
  'theme.dark': 'Dark',
  'theme.system': 'System',
  'lang.label': 'Language',
  'lang.en': 'English',
  'lang.es': 'Español',
  'hero.title': 'Apps by 0xVera',
  'hero.subtitle':
    'Independent applications designed around utility, privacy and straightforward user experiences.',
  'catalog.title': 'Applications',
  'catalog.subtitle': 'Browse published and upcoming apps from 0xVera Devs.',
  'catalog.viewDetails': 'View details',
  'catalog.empty': 'No applications are listed yet.',
  'about.title': 'About',
  'about.body':
    '0xVera Devs is the public developer identity used for a collection of independent software projects and applications.',
  'contact.title': 'Contact',
  'contact.supportLabel': 'App support',
  'contact.generalLabel': 'General contact',
  'contact.supportHint': 'For questions about a specific application.',
  'contact.generalHint': 'For general inquiries about 0xVera Devs.',
  'status.available': 'Available',
  'status.coming-soon': 'Coming soon',
  'status.in-development': 'In development',
  'status.unavailable': 'Unavailable',
  'price.free': 'Free',
  'price.paid': 'Paid',
  'price.freemium': 'Freemium',
  'platform.android': 'Android',
  'platform.ios': 'iOS',
  'platform.web': 'Web',
  'app.developer': 'Developer',
  'app.status': 'Status',
  'app.platforms': 'Platforms',
  'app.price': 'Price',
  'app.version': 'Version',
  'app.updated': 'Updated',
  'app.minimumAndroid': 'Minimum Android',
  'app.minimumIos': 'Minimum iOS',
  'app.hasAds': 'Advertising',
  'app.hasAnalytics': 'Analytics',
  'app.requiresAccount': 'Account required',
  'app.worksOffline': 'Works offline',
  'app.yes': 'Yes',
  'app.no': 'No',
  'app.features': 'Features',
  'app.permissions': 'Permissions',
  'app.screenshots': 'Screenshots',
  'app.links': 'Links',
  'app.privacy': 'Privacy policy',
  'app.support': 'Support',
  'app.terms': 'Terms',
  'app.web': 'Website',
  'app.repository': 'Repository',
  'app.playStore': 'Google Play',
  'app.appStore': 'App Store',
  'app.comingSoonPlay': 'Coming soon on Google Play',
  'app.comingSoonStore': 'Coming soon',
  'app.backToCatalog': 'Back to apps',
  'app.incompleteNotice':
    'Some details for this application are still being prepared and will be updated before publication.',
  'footer.identity': '0xVera Devs',
  'footer.tagline': 'Independent applications with a focus on utility and privacy.',
  'footer.rights': 'All rights reserved.',
  'consent.title': 'Analytics preference',
  'consent.body':
    'We use optional analytics to understand aggregate usage of this site. No analytics cookies are set until you accept.',
  'consent.accept': 'Accept analytics',
  'consent.reject': 'Reject',
  'consent.manage': 'Manage analytics',
  'consent.savedAccept': 'Analytics enabled.',
  'consent.savedReject': 'Analytics disabled.',
  'notFound.title': 'Page not found',
  'notFound.body': 'The page you requested does not exist or has been moved.',
  'notFound.cta': 'Return home',
  'legal.draftNotice': 'This page is temporary and not ready for indexing.',
  'legal.updated': 'Last updated',
  'support.title': 'Support',
  'support.emailLabel': 'Email support',
  'support.includeTitle': 'Please include',
  'support.warningTitle': 'Do not send sensitive data',
};

const es: Dictionary = {
  'nav.apps': 'Apps',
  'nav.about': 'Acerca de',
  'nav.contact': 'Contacto',
  'nav.privacy': 'Privacidad',
  'nav.cookies': 'Cookies',
  'nav.home': 'Inicio',
  'nav.skip': 'Saltar al contenido',
  'nav.menu': 'Principal',
  'theme.label': 'Tema de color',
  'theme.light': 'Claro',
  'theme.dark': 'Oscuro',
  'theme.system': 'Sistema',
  'lang.label': 'Idioma',
  'lang.en': 'English',
  'lang.es': 'Español',
  'hero.title': 'Apps de 0xVera',
  'hero.subtitle':
    'Aplicaciones independientes diseñadas en torno a la utilidad, la privacidad y una experiencia directa.',
  'catalog.title': 'Aplicaciones',
  'catalog.subtitle': 'Explora las apps publicadas y próximas de 0xVera Devs.',
  'catalog.viewDetails': 'Ver detalles',
  'catalog.empty': 'Todavía no hay aplicaciones listadas.',
  'about.title': 'Acerca de',
  'about.body':
    '0xVera Devs es la identidad pública de desarrollo utilizada para una colección de proyectos y aplicaciones de software independientes.',
  'contact.title': 'Contacto',
  'contact.supportLabel': 'Soporte de apps',
  'contact.generalLabel': 'Contacto general',
  'contact.supportHint': 'Para preguntas sobre una aplicación concreta.',
  'contact.generalHint': 'Para consultas generales sobre 0xVera Devs.',
  'status.available': 'Disponible',
  'status.coming-soon': 'Próximamente',
  'status.in-development': 'En desarrollo',
  'status.unavailable': 'No disponible',
  'price.free': 'Gratis',
  'price.paid': 'De pago',
  'price.freemium': 'Freemium',
  'platform.android': 'Android',
  'platform.ios': 'iOS',
  'platform.web': 'Web',
  'app.developer': 'Desarrollador',
  'app.status': 'Estado',
  'app.platforms': 'Plataformas',
  'app.price': 'Precio',
  'app.version': 'Versión',
  'app.updated': 'Actualización',
  'app.minimumAndroid': 'Android mínimo',
  'app.minimumIos': 'iOS mínimo',
  'app.hasAds': 'Publicidad',
  'app.hasAnalytics': 'Analítica',
  'app.requiresAccount': 'Requiere cuenta',
  'app.worksOffline': 'Funciona sin conexión',
  'app.yes': 'Sí',
  'app.no': 'No',
  'app.features': 'Funciones',
  'app.permissions': 'Permisos',
  'app.screenshots': 'Capturas',
  'app.links': 'Enlaces',
  'app.privacy': 'Política de privacidad',
  'app.support': 'Soporte',
  'app.terms': 'Términos',
  'app.web': 'Sitio web',
  'app.repository': 'Repositorio',
  'app.playStore': 'Google Play',
  'app.appStore': 'App Store',
  'app.comingSoonPlay': 'Próximamente en Google Play',
  'app.comingSoonStore': 'Próximamente',
  'app.backToCatalog': 'Volver a las apps',
  'app.incompleteNotice':
    'Algunos detalles de esta aplicación todavía se están preparando y se actualizarán antes de su publicación.',
  'footer.identity': '0xVera Devs',
  'footer.tagline': 'Aplicaciones independientes con foco en utilidad y privacidad.',
  'footer.rights': 'Todos los derechos reservados.',
  'consent.title': 'Preferencia de analítica',
  'consent.body':
    'Usamos analítica opcional para entender el uso agregado de este sitio. No se establecen cookies de analítica hasta que aceptes.',
  'consent.accept': 'Aceptar analítica',
  'consent.reject': 'Rechazar',
  'consent.manage': 'Gestionar analítica',
  'consent.savedAccept': 'Analítica activada.',
  'consent.savedReject': 'Analítica desactivada.',
  'notFound.title': 'Página no encontrada',
  'notFound.body': 'La página solicitada no existe o se ha movido.',
  'notFound.cta': 'Volver al inicio',
  'legal.draftNotice': 'Esta página es temporal y no está lista para indexación.',
  'legal.updated': 'Última actualización',
  'support.title': 'Soporte',
  'support.emailLabel': 'Soporte por email',
  'support.includeTitle': 'Incluye, si puedes',
  'support.warningTitle': 'No envíes datos sensibles',
};

const dictionaries: Record<Locale, Dictionary> = { en, es };

export function t(locale: Locale, key: string): string {
  return dictionaries[locale][key] ?? dictionaries.en[key] ?? key;
}
